[package]
name = "qdb-cli2"
version = "0.1.0"
authors = ["VaskillerDev <Vaskoooo9241@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
serde = "1.0.104"
regex = "1.3.5"
lazy_static = "1.4.0"
simple_logger = "1.6.0"
log = "0.4.8"